global:
  scrape_interval: 5s
  evaluation_interval : 10s
  external_labels:
    monitor: 'dm-monitor'

scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - prometheus:9090
- job_name: cadvisor
  scrape_interval: 1m
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node-exporter
  scrape_interval: 1m
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: 'Check-Order-Http-Endpoint'
  scrape_interval: 10s 
  metrics_path: /probe
  params:
    module: ['http_2xx']  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - https://DM-IP:443/order-service/poll
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115  # The blackbox exporte

- job_name: 'Check-Result-Http-Endpoint'
  scrape_interval: 10s 
  metrics_path: /probe
  params:
    module: ['http_2xx']  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - https://DM-IP:443/result-service/poll
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115  # The blackbox exporte      
      
- job_name: 'TCP-blackbox'
  scrape_interval: 10s
  metrics_path: /probe
  params:
    module: [tcp_connect]  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - DM-IP:8898
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115  # The blackbox exporte

alerting:
  alertmanagers:
    - static_configs:
      - targets: 
        - alertmanager:9093

rule_files:
- 'alert.rules'
