{
 "title": "X800 Datamanager Docker Containers Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "X800 Datamanager Docker Containers Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><table><tr><td><h1>Roche X800 Data Manager<h1></td><td><img src=http://www.x800dm.com:4000/assets/images/roche_logo_global_header.svg height=70></img></td></tr></table>"
  },
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(ALERTS)" }
     ]
    },
    {
     "title": "Targets Online",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(up)" }
     ]
    },
    {
     "title": "Running Containers",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 15, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "predict_linear(node_filesystem_free_bytes{mountpoint=\"/\"}[4h], 4 * 3600) "
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 7, "x": 12, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
      }
     ]
    },
    {
     "title": "Node Network Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "RECEIVE"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "TRANSMIT"
      }
     ]
    },
    {
     "title": "Node Mermory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
       "legendFormat": "Used Memory"
      },
      {
       "expr": "sum(node_memory_MemAvailable_bytes)",
       "legendFormat": "Available Memory"
      }
     ]
    },
    {
     "title": "Filesystem Available",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
       "legendFormat": "Free Storage"
      }
     ]
    }
   ]
  },
  { "title": "Container Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{name!=\"\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 12, "y": 5 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor  Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[2m]))\r\n  BY (instance) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[2m]))\r\n  BY (instance) / 1024 / 1024"
    }
   ]
  }
 ]
}